### ISSUE TITLE
Python3 install error

### ISSUE THREAD

**Issue by leon-wu** [ziplokk1/scrapy-amazon-robot-middleware#3]
I am getting an error with install the middleware. I am using Python3, does this middleware support Python3?

`Collecting git+https://github.com/ziplokk1/scrapy-amazon-robot-middleware.git
  Cloning https://github.com/ziplokk1/scrapy-amazon-robot-middleware.git to \temp\pip-fjqzfpas-build
Collecting beautifulsoup (from scrapy-amazon-robot-middleware==0.1.0)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "temp\pip-build-vzurk9qu\beautifulsoup\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
`

**Comment by ziplokk1** [comment]
Unfortunately I haven't been able to add python 3 compatibility with the
library yet.

**Comment by hellpanderrr** [comment]
To make CaptchaBuster itself work in python3 you need to fix the imports:
```
try:
    from StringIO import StringIO
except ImportError:
    from io import BytesIO as StringIO
try:
    xrange
except NameError:
    xrange = range 
```
(or replace StringIO -> BytesIO everywhere)

**Comment by BlackToothGrin96** [comment]
I have fixed this incompatibility issue and submitted a pull request
